version: 2
jobs:
  build:
    working_directory: ~/yiq
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Node.js version
          command: 'echo "ℹ️  Node.js version: $(node --version)"'
      - run:
          name: Yarn version
          command: 'echo "ℹ️  Yarn version: $(yarn --version)"'
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn lint
      - run: yarn test
